import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from '../components/Navbar';
import { Poppins } from "next/font/google";


const poppins = Poppins({
    subsets: ["latin"],
    weight: ["400", "600", "700"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en" className={poppins.className}>
      <head>
          <title>TP10-Website</title>
      </head>
      <body>
      <Navbar />
      {children}
      </body>
      </html>
  );
}


